name: Test on Dev PR

on:
  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: windows-latest
    env:
      TEST_PROJECT: EtwSuite.Tests\EtwSuite.Tests.csproj
      BUILD_CONFIGURATION: Debug
      BUILD_PLATFORM: x64
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      
      - name: Restore dependencies
        run: dotnet restore $env:TEST_PROJECT /p:Platform=$env:BUILD_PLATFORM
      
      - name: Build
        run: dotnet build $env:TEST_PROJECT --configuration $env:BUILD_CONFIGURATION --no-restore /p:Platform=$env:BUILD_PLATFORM
      
      - name: Run Tests
        run: dotnet test $env:TEST_PROJECT --configuration $env:BUILD_CONFIGURATION --no-build --verbosity normal /p:Platform=$env:BUILD_PLATFORM
